// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBB2nS7isUhI_FkBrO_eX3sUX9bWxwLXE',
    appId: '1:955930209044:web:87fc24a84a22694af3b001',
    messagingSenderId: '955930209044',
    projectId: 'makerfriend-a3cc3',
    authDomain: 'makerfriend-a3cc3.firebaseapp.com',
    storageBucket: 'makerfriend-a3cc3.firebasestorage.app',
    measurementId: 'G-GKMTLJFEMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc5ZrXNA1f-uE-_Q5oXvfQ64hT-3wUkM0',
    appId: '1:955930209044:android:c58f92f17138957df3b001',
    messagingSenderId: '955930209044',
    projectId: 'makerfriend-a3cc3',
    storageBucket: 'makerfriend-a3cc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBALq2_5umPhDasKgoeiEq-NNe_wLnhiMU',
    appId: '1:955930209044:ios:1f2d93ed9b9319c6f3b001',
    messagingSenderId: '955930209044',
    projectId: 'makerfriend-a3cc3',
    storageBucket: 'makerfriend-a3cc3.firebasestorage.app',
    iosClientId: '955930209044-7mh4ct4pjkorl40ikhd474gjdsrcjltv.apps.googleusercontent.com',
    iosBundleId: 'com.example.makerFriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBALq2_5umPhDasKgoeiEq-NNe_wLnhiMU',
    appId: '1:955930209044:ios:4b44faf3b7e4741cf3b001',
    messagingSenderId: '955930209044',
    projectId: 'makerfriend-a3cc3',
    storageBucket: 'makerfriend-a3cc3.firebasestorage.app',
    iosClientId: '955930209044-7mh4ct4pjkorl40ikhd474gjdsrcjltv.apps.googleusercontent.com',
    iosBundleId: 'com.example.makerFriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBB2nS7isUhI_FkBrO_eX3sUX9bWxwLXE',
    appId: '1:955930209044:web:55211602122cb9d5f3b001',
    messagingSenderId: '955930209044',
    projectId: 'makerfriend-a3cc3',
    authDomain: 'makerfriend-a3cc3.firebaseapp.com',
    storageBucket: 'makerfriend-a3cc3.firebasestorage.app',
    measurementId: 'G-6F9FTW2PMK',
  );
}